// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etozvnlfukmfqsegjwzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0b3p2bmxmdWttZnFzZWdqd3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODA5OTAsImV4cCI6MjA2MDk1Njk5MH0.CIBohfoc6I7CPZJtU2b7ewAAzbc-RZwRwO7kQvNFC14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});